// <auto-generated />
using System;
using CMCS.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMCS.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251118155909_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMCS.Web.Models.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApproverId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DecisionAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("CMCS.Web.Models.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("CMCS.Web.Models.ClaimLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<decimal>("Hours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimLines");
                });

            modelBuilder.Entity("CMCS.Web.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("CMCS.Web.Models.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DefaultHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("Lecturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "62********89",
                            BankName = "First National Bank",
                            CreatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9636),
                            DefaultHourlyRate = 500m,
                            Department = "Computer Science",
                            Email = "sarah.johnson@university.ac.za",
                            EmployeeNumber = "EMP001",
                            FullName = "Dr. Sarah Johnson",
                            IsActive = true,
                            PhoneNumber = "011-234-5678",
                            TaxNumber = "9*******3",
                            UpdatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9637)
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "25********67",
                            BankName = "Standard Bank",
                            CreatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9653),
                            DefaultHourlyRate = 550m,
                            Department = "Information Technology",
                            Email = "michael.chen@university.ac.za",
                            EmployeeNumber = "EMP002",
                            FullName = "Prof. Michael Chen",
                            IsActive = true,
                            PhoneNumber = "011-234-5679",
                            TaxNumber = "8*******2",
                            UpdatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9654)
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "40********12",
                            BankName = "ABSA",
                            CreatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9662),
                            DefaultHourlyRate = 450m,
                            Department = "Software Engineering",
                            Email = "thandi.nkosi@university.ac.za",
                            EmployeeNumber = "EMP003",
                            FullName = "Dr. Thandi Nkosi",
                            IsActive = true,
                            PhoneNumber = "011-234-5680",
                            TaxNumber = "7*******5",
                            UpdatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9663)
                        },
                        new
                        {
                            Id = 4,
                            AccountNumber = "18********34",
                            BankName = "Nedbank",
                            CreatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9670),
                            DefaultHourlyRate = 600m,
                            Department = "Data Science",
                            Email = "james.anderson@university.ac.za",
                            EmployeeNumber = "EMP004",
                            FullName = "Prof. James Anderson",
                            IsActive = true,
                            PhoneNumber = "011-234-5681",
                            TaxNumber = "6*******8",
                            UpdatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9671)
                        },
                        new
                        {
                            Id = 5,
                            AccountNumber = "14********56",
                            BankName = "Capitec",
                            CreatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9678),
                            DefaultHourlyRate = 480m,
                            Department = "Information Systems",
                            Email = "lerato.molefe@university.ac.za",
                            EmployeeNumber = "EMP005",
                            FullName = "Dr. Lerato Molefe",
                            IsActive = true,
                            PhoneNumber = "011-234-5682",
                            TaxNumber = "5*******1",
                            UpdatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9678)
                        },
                        new
                        {
                            Id = 6,
                            AccountNumber = "62********91",
                            BankName = "First National Bank",
                            CreatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9692),
                            DefaultHourlyRate = 700m,
                            Department = "Computer Science",
                            Email = "david.williams@university.ac.za",
                            EmployeeNumber = "EMP006",
                            FullName = "Prof. David Williams",
                            IsActive = true,
                            PhoneNumber = "011-234-5683",
                            TaxNumber = "4*******9",
                            UpdatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9693)
                        },
                        new
                        {
                            Id = 7,
                            AccountNumber = "40********78",
                            BankName = "ABSA",
                            CreatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9700),
                            DefaultHourlyRate = 650m,
                            Department = "Cybersecurity",
                            Email = "nomsa.dlamini@university.ac.za",
                            EmployeeNumber = "EMP007",
                            FullName = "Dr. Nomsa Dlamini",
                            IsActive = true,
                            PhoneNumber = "011-234-5684",
                            TaxNumber = "3*******4",
                            UpdatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9701)
                        },
                        new
                        {
                            Id = 8,
                            AccountNumber = "25********45",
                            BankName = "Standard Bank",
                            CreatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9707),
                            DefaultHourlyRate = 520m,
                            Department = "Software Engineering",
                            Email = "kevin.patel@university.ac.za",
                            EmployeeNumber = "EMP008",
                            FullName = "Dr. Kevin Patel",
                            IsActive = true,
                            PhoneNumber = "011-234-5685",
                            TaxNumber = "2*******7",
                            UpdatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9708)
                        },
                        new
                        {
                            Id = 9,
                            AccountNumber = "18********92",
                            BankName = "Nedbank",
                            CreatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9715),
                            DefaultHourlyRate = 490m,
                            Department = "Web Development",
                            Email = "amanda.brown@university.ac.za",
                            EmployeeNumber = "EMP009",
                            FullName = "Prof. Amanda Brown",
                            IsActive = true,
                            PhoneNumber = "011-234-5686",
                            TaxNumber = "1*******6",
                            UpdatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9715)
                        },
                        new
                        {
                            Id = 10,
                            AccountNumber = "14********23",
                            BankName = "Capitec",
                            CreatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9725),
                            DefaultHourlyRate = 530m,
                            Department = "Database Management",
                            Email = "sipho.khumalo@university.ac.za",
                            EmployeeNumber = "EMP010",
                            FullName = "Dr. Sipho Khumalo",
                            IsActive = true,
                            PhoneNumber = "011-234-5687",
                            TaxNumber = "9*******0",
                            UpdatedAt = new DateTime(2025, 11, 18, 15, 59, 9, 79, DateTimeKind.Utc).AddTicks(9726)
                        });
                });

            modelBuilder.Entity("CMCS.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@university.ac.za",
                            FullName = "Admin User",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "coordinator@university.ac.za",
                            FullName = "Coordinator User",
                            Role = 1
                        });
                });

            modelBuilder.Entity("CMCS.Web.Models.Approval", b =>
                {
                    b.HasOne("CMCS.Web.Models.Claim", "Claim")
                        .WithMany("Approvals")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("CMCS.Web.Models.Claim", b =>
                {
                    b.HasOne("CMCS.Web.Models.Lecturer", "Lecturer")
                        .WithMany("Claims")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("CMCS.Web.Models.ClaimLine", b =>
                {
                    b.HasOne("CMCS.Web.Models.Claim", "Claim")
                        .WithMany("Lines")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("CMCS.Web.Models.Document", b =>
                {
                    b.HasOne("CMCS.Web.Models.Claim", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("CMCS.Web.Models.Claim", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Documents");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("CMCS.Web.Models.Lecturer", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
