// <auto-generated />
using System;
using CMCS.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMCS.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251118180100_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMCS.Web.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("LecturerId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CMCS.Web.Models.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApproverId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DecisionAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("CMCS.Web.Models.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("CMCS.Web.Models.ClaimLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<decimal>("Hours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimLines");
                });

            modelBuilder.Entity("CMCS.Web.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("CMCS.Web.Models.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DefaultHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("Lecturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "62********89",
                            BankName = "First National Bank",
                            CreatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1079),
                            DefaultHourlyRate = 500m,
                            Department = "Computer Science",
                            Email = "sarah.johnson@university.ac.za",
                            EmployeeNumber = "EMP001",
                            FullName = "Dr. Sarah Johnson",
                            IsActive = true,
                            PhoneNumber = "011-234-5678",
                            TaxNumber = "9*******3",
                            UpdatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1081)
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "25********67",
                            BankName = "Standard Bank",
                            CreatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1093),
                            DefaultHourlyRate = 550m,
                            Department = "Information Technology",
                            Email = "michael.chen@university.ac.za",
                            EmployeeNumber = "EMP002",
                            FullName = "Prof. Michael Chen",
                            IsActive = true,
                            PhoneNumber = "011-234-5679",
                            TaxNumber = "8*******2",
                            UpdatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1094)
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "40********12",
                            BankName = "ABSA",
                            CreatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1102),
                            DefaultHourlyRate = 450m,
                            Department = "Software Engineering",
                            Email = "thandi.nkosi@university.ac.za",
                            EmployeeNumber = "EMP003",
                            FullName = "Dr. Thandi Nkosi",
                            IsActive = true,
                            PhoneNumber = "011-234-5680",
                            TaxNumber = "7*******5",
                            UpdatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1103)
                        },
                        new
                        {
                            Id = 4,
                            AccountNumber = "18********34",
                            BankName = "Nedbank",
                            CreatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1111),
                            DefaultHourlyRate = 600m,
                            Department = "Data Science",
                            Email = "james.anderson@university.ac.za",
                            EmployeeNumber = "EMP004",
                            FullName = "Prof. James Anderson",
                            IsActive = true,
                            PhoneNumber = "011-234-5681",
                            TaxNumber = "6*******8",
                            UpdatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1112)
                        },
                        new
                        {
                            Id = 5,
                            AccountNumber = "14********56",
                            BankName = "Capitec",
                            CreatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1120),
                            DefaultHourlyRate = 480m,
                            Department = "Information Systems",
                            Email = "lerato.molefe@university.ac.za",
                            EmployeeNumber = "EMP005",
                            FullName = "Dr. Lerato Molefe",
                            IsActive = true,
                            PhoneNumber = "011-234-5682",
                            TaxNumber = "5*******1",
                            UpdatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1121)
                        },
                        new
                        {
                            Id = 6,
                            AccountNumber = "62********91",
                            BankName = "First National Bank",
                            CreatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1134),
                            DefaultHourlyRate = 700m,
                            Department = "Computer Science",
                            Email = "david.williams@university.ac.za",
                            EmployeeNumber = "EMP006",
                            FullName = "Prof. David Williams",
                            IsActive = true,
                            PhoneNumber = "011-234-5683",
                            TaxNumber = "4*******9",
                            UpdatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1135)
                        },
                        new
                        {
                            Id = 7,
                            AccountNumber = "40********78",
                            BankName = "ABSA",
                            CreatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1142),
                            DefaultHourlyRate = 650m,
                            Department = "Cybersecurity",
                            Email = "nomsa.dlamini@university.ac.za",
                            EmployeeNumber = "EMP007",
                            FullName = "Dr. Nomsa Dlamini",
                            IsActive = true,
                            PhoneNumber = "011-234-5684",
                            TaxNumber = "3*******4",
                            UpdatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1143)
                        },
                        new
                        {
                            Id = 8,
                            AccountNumber = "25********45",
                            BankName = "Standard Bank",
                            CreatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1150),
                            DefaultHourlyRate = 520m,
                            Department = "Software Engineering",
                            Email = "kevin.patel@university.ac.za",
                            EmployeeNumber = "EMP008",
                            FullName = "Dr. Kevin Patel",
                            IsActive = true,
                            PhoneNumber = "011-234-5685",
                            TaxNumber = "2*******7",
                            UpdatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1151)
                        },
                        new
                        {
                            Id = 9,
                            AccountNumber = "18********92",
                            BankName = "Nedbank",
                            CreatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1159),
                            DefaultHourlyRate = 490m,
                            Department = "Web Development",
                            Email = "amanda.brown@university.ac.za",
                            EmployeeNumber = "EMP009",
                            FullName = "Prof. Amanda Brown",
                            IsActive = true,
                            PhoneNumber = "011-234-5686",
                            TaxNumber = "1*******6",
                            UpdatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1160)
                        },
                        new
                        {
                            Id = 10,
                            AccountNumber = "14********23",
                            BankName = "Capitec",
                            CreatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1170),
                            DefaultHourlyRate = 530m,
                            Department = "Database Management",
                            Email = "sipho.khumalo@university.ac.za",
                            EmployeeNumber = "EMP010",
                            FullName = "Dr. Sipho Khumalo",
                            IsActive = true,
                            PhoneNumber = "011-234-5687",
                            TaxNumber = "9*******0",
                            UpdatedAt = new DateTime(2025, 11, 18, 18, 0, 58, 485, DateTimeKind.Utc).AddTicks(1171)
                        });
                });

            modelBuilder.Entity("CMCS.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@university.ac.za",
                            FullName = "Admin User",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "coordinator@university.ac.za",
                            FullName = "Coordinator User",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CMCS.Web.Models.ApplicationUser", b =>
                {
                    b.HasOne("CMCS.Web.Models.Lecturer", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("CMCS.Web.Models.Approval", b =>
                {
                    b.HasOne("CMCS.Web.Models.Claim", "Claim")
                        .WithMany("Approvals")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("CMCS.Web.Models.Claim", b =>
                {
                    b.HasOne("CMCS.Web.Models.Lecturer", "Lecturer")
                        .WithMany("Claims")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("CMCS.Web.Models.ClaimLine", b =>
                {
                    b.HasOne("CMCS.Web.Models.Claim", "Claim")
                        .WithMany("Lines")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("CMCS.Web.Models.Document", b =>
                {
                    b.HasOne("CMCS.Web.Models.Claim", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CMCS.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CMCS.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMCS.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CMCS.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMCS.Web.Models.Claim", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Documents");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("CMCS.Web.Models.Lecturer", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
